#define NODE_TYPE_START 0
#define NODE_TYPE_STRAIGHT 1
#define NODE_TYPE_LEFT 2
#define NODE_TYPE_RIGHT 3
#define NODE_TYPE_DEADEND 4
#define NODE_TYPE_T 5
#define NODE_TYPE_CROSS 6
#define NODE_TYPE_GOAL 7
#define NODE_TYPE_LEFT_STRAIGHT 8
#define NODE_TYPE_RIGHT_STRAIGHT 9
#define NODE_TYPE_U_TURN 10

